config/routes.rb
BaseballHackDayPre::Application.routes.draw do
  root :to => 'players#index'

  resources :players, :only => [:index, :show] do
    resources :seasons, :only => [:index, :show]
  end

  resources :seasons, :only => [:index, :show]
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :seasons

  JSON_ATTRIBUTES = {
    :show  => (Player.column_names - ['created_at', 'updated_at']),
    :index => ['id', 'first_name', 'last_name', 'full_name', 'wwar_norm', 'hof_status', 'wwar_status']
  }

  def self.find_or_create_by(attributes_hash)
    Player.where(:full_name => attributes_hash['full_name']).first ||
      Player.create(attributes_hash.slice(*Player.column_names))
  end

  def as_json(options = {})
    options.reverse_merge!(:view => :show, :with_seasons => false)

    content = attributes.slice(*JSON_ATTRIBUTES[options[:view]])

    if options[:with_seasons]
      content.merge!(:seasons => seasons.as_json)
    end

    content
  end

  def to_param
    full_name.gsub(/ /, '-')
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :player

  def as_json(options={})
    attributes.slice(*(Season.column_names - ['created_at', 'updated_at']))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    respond_to do |format|
      format.html { @players = Player.order("wwar_norm DESC") }

      format.json do
        if params[:with_seasons]
          render :json => Player.all(:include => :seasons).as_json(:with_seasons => true, :view => :index)
        else
          render :json => Player.all.as_json(:view => :index)
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html { @player = Player.find_by_full_name(params[:id].gsub(/-/, ' ')) }

      format.json do
        if params[:with_seasons]
          render :json => Player.find_by_id(params[:id]).as_json(:with_seasons => true)
        else
          render :json => Player.find_by_id(params[:id]).as_json
        end
      end
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    if params[:player_id].present?
      render json: Player.find_by_id(params[:player_id]).seasons.order('year asc').as_json
    else
      render json: Season.order('year asc, id asc').as_json
    end
  end

  def show
    render json: Season.find_by_id(params[:id]).as_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  PLAYER_TOTAL_STAT_ATTRIBUTES = [
    # everyone
    "wwar_norm", "war_pos", "war_p", "war_tot", "war_162", "wae", "wam", "wwpa",
    # pitchers
    "era", "era_plus", "p_w", "p_l", "p_sv",
    # batters
    "ba", "obp", "slg", "ops_plus"
  ]

  PLAYER_SEASON_STAT_ATTRIBUTES = [
    "year", "age", "war_pos", "war_p", "war_tot",
    "wae", "wam",
    "p_w", "p_l", "p_sv", "p_g", "p_gs", "p_cg", "p_sho", "p_ip",
    "p_h", "p_r", "p_er", "p_hr", "p_bb", "p_so", "era",
    "b_g", "b_pa", "b_ab", "b_r", "b_h", "b_2b", "b_3b", "b_hr", "b_rbi",
    "b_bb", "b_so", "b_sb", "b_cs",
    "ba", "obp", "slg", "ops"
  ]

  def wwar_hall_count
    @players.select(&:wwar_status).size
  end

  def whos_next_count
    @players.select(&:future_wwar).size
  end

  def whos_in_count
    @players.select{|p| p.wwar_status && p.hof_status != 'hof'}.size
  end

  def whos_out_count
    @players.select{|p| !p.wwar_status && p.hof_status == 'hof'}.size
  end

  def player_class player
    [
      "pos-#{player.pos}",
      player.hof_status || '',
      (player.wwar_status ? 'wwar' : ''),
      (player.future_wwar ? 'future' : '')
    ].join(' ').squish
  end

  def player_image player
    "/images/#{player.first_name.gsub(/ /, '')}_#{player.last_name}.jpg".downcase
  end

  def human_column(column)
    column.sub(/^[pb]_/, '').humanize.upcase.sub(/ NORM/, '').sub(/WAR /, 'WAR/').sub('PLUS', '+')
  end

  def player_total_stats player
    columns = []
    values = []

    PLAYER_TOTAL_STAT_ATTRIBUTES.each do |column|
      unless player.attributes[column].blank?
        columns << [human_column(column), translation_or_default(column)]
        values << format_attribute(player, column)
      end
    end

    [columns, values]
  end

  def format_attribute(obj, column)
    value = obj.attributes[column]

    case column
    when 'era'
      sprintf("%.2f", value) if value.present?
    when "ba", "obp", "ops", "slg"
      sprintf("%.3f", value).sub(/^0/, '') if value.present?
    else
      value
    end
  end

  def player_season_stats player
    columns = ActiveSupport::OrderedHash.new

    player.seasons.order("year ASC").each do |season|
      PLAYER_SEASON_STAT_ATTRIBUTES.each do |column|
        columns[column] ||= []
        columns[column] << format_attribute(season, column)
      end
    end

    columns.reject! do |col, values|
      values.all?(&:blank?)
    end

    [
      columns.keys.map{|c| [human_column(c), translation_or_default(c)]},
      columns.values.transpose
    ]
  end

  def has_honors?
    @player.hof_status == 'hof' || @player.wwar_status || @player.future_wwar
  end

  def translation_or_default(key)
    if I18n.backend.send(:lookup, :en, key).present?
      t(key)
    else
      key.capitalize
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  <title>Red Sox Hall of wWAR</title>
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-379490-11']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>

<header id="main">
  <h1><a href="/">Red Sox Hall of <abbr title="Weighted Wins Above Replacement">wWAR</abbr></a></h1>
</header>

<%= yield %>

<footer>
  <p>
    The Red Sox Hall of wWAR was created at <a href="http://baseballhackday.com">Baseball Hack Day</a> in March 2012 by
    <a href="http://darowski.com">Adam Darowski</a>, <a href="http://semanticart.com/">Jeffrey Chupp</a>,
    and <a href="https://twitter.com/#!/beantownsports">Adam Bailey</a>. Wins Above Replacement (WAR) data lovingly
    pulled from <a href="http://baseball-reference.com">Baseball-Reference</a>.</a>
  </p>
</footer>

</body>
</html>

app/views/players/index.html.haml
%section#about
  %p
    This project is based on the <a href="http://darowski.com/hall-of-wwar">Hall of wWAR</a>, an alternate Hall of Fame populated by a single statistic.
    That statistic, <strong>weighted Wins Above Replacement</strong> (or <strong>wWAR</strong>), combines the value of all aspects of a player’s contributions (hitting, pitching,
    fielding, baserunning, position, etc.) and gives additional adjustments for peak performance, playoff heroics, and season length.
    Read more <a href="http://darowski.com/hall-of-wwar/about">about wWAR</a> for more information.
  %p
    The Red Sox Hall of wWAR takes the same approach, but instead re-populates the <a href="http://boston.redsox.mlb.com/bos/history/feature_hall_of_fame.jsp">Red Sox Hall of Fame</a>.
    There are currently #{wwar_hall_count} players in the Red Sox Hall of <strong>Fame</strong>. The Red Sox Hall of <strong>wWAR</strong> is populated by the top #{wwar_hall_count}
    eligible players in franchise history, as ranked by the wWAR they accumulated with Boston. During this process, #{whos_out_count} players were removed from the Red Sox Hall of Fame
    and were replaced by #{whos_in_count} others. There are also #{whos_next_count} players who are not yet eligible for the Red Sox Hall of Fame that already fit the induction criteria.
    This site includes data for every Red Sox player who accumulated 5 or more Wins Above Replacement with the franchise.

%section#toggles
  %dl
    %dt View:
    %dd
      %a#show-hall{:href => "#show-hall"}
        Red Sox Hall of wWAR
        %span (#{wwar_hall_count})
    %dd
      %a#show-all{:href => "#show-all"}
        All Red Sox Players with 5+ WAR
        %span (#{@players.size})
  %dl#positions
    %dt Positions:
    %dd
      %a#show-p{:href => "#show-p"}
        P
        %span
    %dd
      %a#show-c{:href => "#show-c"}
        C
        %span
    %dd
      %a#show-1b{:href => "#show-1b"}
        1B
        %span
    %dd
      %a#show-2b{:href => "#show-2b"}
        2B
        %span
    %dd
      %a#show-3b{:href => "#show-3b"}
        3B
        %span
    %dd
      %a#show-ss{:href => "#show-ss"}
        SS
        %span
    %dd
      %a#show-lf{:href => "#show-lf"}
        LF
        %span
    %dd
      %a#show-cf{:href => "#show-cf"}
        CF
        %span
    %dd
      %a#show-rf{:href => "#show-rf"}
        RF
        %span
    %dd
      %a#show-dh{:href => "#show-dh"}
        DH
        %span
  %dl#adjustments
    %dt Adjustments:
    %dd
      %a#whos-in{:href => "#whos-in"}
        Who is Added?
        %span (#{whos_in_count})
    %dd
      %a#whos-out{:href => "#whos-out"}
        Who is Removed?
        %span (#{whos_out_count})
    %dd
      %a#whos-next{:href => "#whos-next"}
        Who Will Be Inducted?
        %span (#{whos_next_count})

%ol#players
  - @players.each do |player|
    %li{:class => player_class(player)}
      = link_to(player_path(player)) do
        %dl
          %dt
            %span.first-name= player.first_name
            %span.last-name= player.last_name
          %dd.position= player.pos
          %dd.value #{player.wwar_norm} wWAR
          %dd.photo
            %img{:src => player_image(player), :alt => player.full_name + ' Photo', :width => '90', :height => '135'}

app/views/players/show.html.haml
%section#player

  %header
    %img{:src => player_image(@player), :alt => @player.full_name + ' Photo', :width => '90', :height => '135'}
    %h1= @player.full_name
    %span#player-position= @player.pos

    %table#player-totals
      - columns, values = player_total_stats(@player)
      %thead
        %tr
          - columns.each do |col|
            %th
              %abbr{:title => col.last}= col.first
      %tbody
        %tr
          - values.each do |value|
            %td= value

  - if has_honors?
    %ul#honors
      - if @player.hof_status == 'hof'
        %li#rs-hof Member of Red Sox Hall of Fame (#{@player.induction_year})

      - if @player.wwar_status
        %li#rs-wwar Member of Red Sox Hall of wWAR

      - if @player.future_wwar
        %li#rs-future Future Member of Red Sox Hall of wWAR

  #seasons-container
    %table#player-seasons
      - columns, rows = player_season_stats(@player)
      %thead
        %tr
          - columns.each do |col|
            %th
              %abbr{:title => col.last}= col.first
      %tbody
        - rows.each do |values|
          %tr
            - values.each do |value|
              %td= value
  %dl#key
    %dt wWAR
    %dd Weighted Wins Above Replacement (adjusted for peak performance, playoff heroics, season length, etc.).
    %dt WAR/pos
    %dd WAR earned as an offensive/position player.
    %dt WAR/p
    %dd WAR earned as a pitcher.
    %dt WAR/tot
    %dd Combined WAR as offensive/position player and pitcher.
    %dt WAR/162
    %dd Total WAR adjusted for season length.
    %dt WAE
    %dd Wins Above Excellence (all single season WAR above 3.0, lower for catchers and relief pitchers).
    %dt WAM
    %dd Wins Above MVP Level (all single season WAR above 6.0, lower for catchers and relief pitchers).
    %dt wWPA
    %dd Weighted Postseason Win Probability Added.
    %dt More
    %dd <a href="http://darowski.com/hall-of-wwar/about">About wWAR</a>.

app/views/seasons/index.html.erb
<h1>Seasons#index</h1>
<p>Find me in app/views/seasons/index.html.erb</p>

app/views/seasons/show.html.erb
<h1>Seasons#show</h1>
<p>Find me in app/views/seasons/show.html.erb</p>